/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VencanjaRouteImport } from './routes/vencanja'
import { Route as RodjendaniRouteImport } from './routes/rodjendani'
import { Route as PunoletstvaRouteImport } from './routes/punoletstva'
import { Route as PoslovniDogadjajiRouteImport } from './routes/poslovni-dogadjaji'
import { Route as KrstenjaRouteImport } from './routes/krstenja'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as GenderRevealRouteImport } from './routes/gender-reveal'
import { Route as GalerijaRouteImport } from './routes/galerija'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const VencanjaRoute = VencanjaRouteImport.update({
  id: '/vencanja',
  path: '/vencanja',
  getParentRoute: () => rootRouteImport,
} as any)
const RodjendaniRoute = RodjendaniRouteImport.update({
  id: '/rodjendani',
  path: '/rodjendani',
  getParentRoute: () => rootRouteImport,
} as any)
const PunoletstvaRoute = PunoletstvaRouteImport.update({
  id: '/punoletstva',
  path: '/punoletstva',
  getParentRoute: () => rootRouteImport,
} as any)
const PoslovniDogadjajiRoute = PoslovniDogadjajiRouteImport.update({
  id: '/poslovni-dogadjaji',
  path: '/poslovni-dogadjaji',
  getParentRoute: () => rootRouteImport,
} as any)
const KrstenjaRoute = KrstenjaRouteImport.update({
  id: '/krstenja',
  path: '/krstenja',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const GenderRevealRoute = GenderRevealRouteImport.update({
  id: '/gender-reveal',
  path: '/gender-reveal',
  getParentRoute: () => rootRouteImport,
} as any)
const GalerijaRoute = GalerijaRouteImport.update({
  id: '/galerija',
  path: '/galerija',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/galerija': typeof GalerijaRoute
  '/gender-reveal': typeof GenderRevealRoute
  '/kontakt': typeof KontaktRoute
  '/krstenja': typeof KrstenjaRoute
  '/poslovni-dogadjaji': typeof PoslovniDogadjajiRoute
  '/punoletstva': typeof PunoletstvaRoute
  '/rodjendani': typeof RodjendaniRoute
  '/vencanja': typeof VencanjaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/galerija': typeof GalerijaRoute
  '/gender-reveal': typeof GenderRevealRoute
  '/kontakt': typeof KontaktRoute
  '/krstenja': typeof KrstenjaRoute
  '/poslovni-dogadjaji': typeof PoslovniDogadjajiRoute
  '/punoletstva': typeof PunoletstvaRoute
  '/rodjendani': typeof RodjendaniRoute
  '/vencanja': typeof VencanjaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/galerija': typeof GalerijaRoute
  '/gender-reveal': typeof GenderRevealRoute
  '/kontakt': typeof KontaktRoute
  '/krstenja': typeof KrstenjaRoute
  '/poslovni-dogadjaji': typeof PoslovniDogadjajiRoute
  '/punoletstva': typeof PunoletstvaRoute
  '/rodjendani': typeof RodjendaniRoute
  '/vencanja': typeof VencanjaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/galerija'
    | '/gender-reveal'
    | '/kontakt'
    | '/krstenja'
    | '/poslovni-dogadjaji'
    | '/punoletstva'
    | '/rodjendani'
    | '/vencanja'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/galerija'
    | '/gender-reveal'
    | '/kontakt'
    | '/krstenja'
    | '/poslovni-dogadjaji'
    | '/punoletstva'
    | '/rodjendani'
    | '/vencanja'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/galerija'
    | '/gender-reveal'
    | '/kontakt'
    | '/krstenja'
    | '/poslovni-dogadjaji'
    | '/punoletstva'
    | '/rodjendani'
    | '/vencanja'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  GalerijaRoute: typeof GalerijaRoute
  GenderRevealRoute: typeof GenderRevealRoute
  KontaktRoute: typeof KontaktRoute
  KrstenjaRoute: typeof KrstenjaRoute
  PoslovniDogadjajiRoute: typeof PoslovniDogadjajiRoute
  PunoletstvaRoute: typeof PunoletstvaRoute
  RodjendaniRoute: typeof RodjendaniRoute
  VencanjaRoute: typeof VencanjaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vencanja': {
      id: '/vencanja'
      path: '/vencanja'
      fullPath: '/vencanja'
      preLoaderRoute: typeof VencanjaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rodjendani': {
      id: '/rodjendani'
      path: '/rodjendani'
      fullPath: '/rodjendani'
      preLoaderRoute: typeof RodjendaniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/punoletstva': {
      id: '/punoletstva'
      path: '/punoletstva'
      fullPath: '/punoletstva'
      preLoaderRoute: typeof PunoletstvaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poslovni-dogadjaji': {
      id: '/poslovni-dogadjaji'
      path: '/poslovni-dogadjaji'
      fullPath: '/poslovni-dogadjaji'
      preLoaderRoute: typeof PoslovniDogadjajiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/krstenja': {
      id: '/krstenja'
      path: '/krstenja'
      fullPath: '/krstenja'
      preLoaderRoute: typeof KrstenjaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gender-reveal': {
      id: '/gender-reveal'
      path: '/gender-reveal'
      fullPath: '/gender-reveal'
      preLoaderRoute: typeof GenderRevealRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galerija': {
      id: '/galerija'
      path: '/galerija'
      fullPath: '/galerija'
      preLoaderRoute: typeof GalerijaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  GalerijaRoute: GalerijaRoute,
  GenderRevealRoute: GenderRevealRoute,
  KontaktRoute: KontaktRoute,
  KrstenjaRoute: KrstenjaRoute,
  PoslovniDogadjajiRoute: PoslovniDogadjajiRoute,
  PunoletstvaRoute: PunoletstvaRoute,
  RodjendaniRoute: RodjendaniRoute,
  VencanjaRoute: VencanjaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
